<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Notifications\ResetPassword;
use Illuminate\Support\Facades\Auth;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($user) {
            $user->activation_token = str_random(30);
        });
    }

    public function gravatar($size = '100')
    {
        $hash = md5(strtolower(trim($this->attributes['email'])));
        return "http://www.gravatar.com/avatar/$hash?s=$size";
    }

    //发送重置密码邮件邮件
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPassword($token));
    }

    //用户与微博的依赖关系
    public function status()
    {
        return $this->hasMany(Status::class);
    }

    //展示微博数据
    public function feed()
    {
        $user_ids = Auth::user()->followings->pluck('id')->toArray();
        array_push($user_ids, Auth::user()->id);
        return Status::whereIn('user_id', $user_ids)
            ->with('user')
            ->orderBy('created_at', 'desc');
    }

    public function followers()
    {
        //设置依赖关系
        return $this->belongsToMany(User::class, 'followers', 'user_id', 'followers_id');
    }

    public function followings()
    {
        return $this->belongsToMany(User::class, 'followers', 'followers_id', 'user_id');
    }

    public function unfollow($users_id)
    {
        if (!is_array($users_id)) {
            $users_id = compact('users_id');
        }
        $this->followings()->detach($users_id);

    }

    public function follow($users_id)
    {
        if (!is_array($users_id)) {
            $users_id = compact('users_id');
        }
        $this->followings()->attach($users_id);

    }

    public function isFollow($users_id)
    {
        return $this->followings()->allRelatedIds()->contains($users_id);
    }
}
